package com.wfp.lmmis.training.model;
// Generated Jan 5, 2021 1:20:21 AM by Hibernate Tools 4.3.1

import com.wfp.lmmis.payroll.model.FiscalYear;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserTraining generated by hbm2java
 */
@Entity
@Table(name = "user_training")
public class UserTraining implements java.io.Serializable {

    private int id;
    private String courseName;
    private String batchName;
    private String trainingName;
    private Date creationDate;
    private Integer createdBy;
    private Integer courseId;
    private Integer batchId;
    private FiscalYear fiscalYear;
    private String restictedUrl;

    public UserTraining() {
    }

    public UserTraining(int id) {
        this.id = id;
    }

    public UserTraining(int id, String courseName, String batchName, String trainingName, Date creationDate, Integer createdBy, Integer courseId,
            Integer batchId) {
        this.id = id;
        this.courseName = courseName;
        this.batchName = batchName;
        this.trainingName = trainingName;
        this.creationDate = creationDate;
        this.createdBy = createdBy;
        this.courseId = courseId;
        this.batchId = batchId;
    }

    @Id

    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "course_name", length = 50)
    public String getCourseName() {
        return this.courseName;
    }

    /**
     *
     * @param courseName
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    @Column(name = "batch_name", length = 50)
    public String getBatchName() {
        return this.batchName;
    }

    /**
     *
     * @param batchName
     */
    public void setBatchName(String batchName) {
        this.batchName = batchName;
    }

    @Column(name = "training_name", length = 50)
    public String getTrainingName() {
        return this.trainingName;
    }

    public void setTrainingName(String trainingName) {
        this.trainingName = trainingName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "creation_date", length = 10)
    public Date getCreationDate() {
        return this.creationDate;
    }

    /**
     *
     * @param creationDate
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Column(name = "created_by")
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "course_id")
    public Integer getCourseId() {
        return this.courseId;
    }

    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    @Column(name = "batch_id")
    public Integer getBatchId() {
        return this.batchId;
    }

    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fiscal_year_id")
    public FiscalYear getFiscalYear() {
        return this.fiscalYear;
    }

    public void setFiscalYear(FiscalYear fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

    @Column(name = "resticted_url", length = 1000)
    public String getRestictedUrl() {
        return restictedUrl;
    }

    public void setRestictedUrl(String restictedUrl) {
        this.restictedUrl = restictedUrl;
    }

}
