/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wfp.lmmis.payroll.model;

import com.wfp.lmmis.beneficiary.model.Beneficiary;
import com.wfp.lmmis.masterdata.model.AccountType;
import com.wfp.lmmis.masterdata.model.Bank;
import com.wfp.lmmis.masterdata.model.Branch;
import com.wfp.lmmis.masterdata.model.MobileBankingProvider;
import com.wfp.lmmis.masterdata.model.PostOfficeBranch;
import com.wfp.lmmis.model.BaseModel;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentInformationHistory generated by hbm2java
 */
@Entity
@Table(name = "payment_information_history")
public class PaymentInformationHistory extends BaseModel implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "account_type_id", referencedColumnName = "id", nullable = true)
    private AccountType accountType;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bank_id", referencedColumnName = "id", nullable = true)
    private Bank bank;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "beneficiary_id", referencedColumnName = "id", nullable = true)
    private Beneficiary beneficiary;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "branch_id", referencedColumnName = "id", nullable = true)
    private Branch branch;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mobile_banking_provider_id", referencedColumnName = "id", nullable = true)
    private MobileBankingProvider mobileBankingProvider;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "post_office_branch_id", referencedColumnName = "id", nullable = true)
    private PostOfficeBranch postOfficeBranch;
    @Column(name = "reason", nullable = true)
    private Integer reason;
    @Column(name = "isbounse_back_update", nullable = true)
    private Integer isbounseBackUpdate;

    @Column(name = "file_base64", nullable = true)
    private String fileBase64;
    @Column(name = "remarks", length = 50, nullable = true)
    private String remarks;
    @Column(name = "payment_type", nullable = true)
    private Integer paymentType;

    @Column(name = "account_no", length = 50, nullable = true)
    private String accountNo;
    @Column(name = "account_name", length = 50, nullable = true)
    private String accountName;

    public PaymentInformationHistory() {
    }

    public PaymentInformationHistory(AccountType accountType, Bank bank, Beneficiary beneficiary, Branch branch,
            MobileBankingProvider mobileBankingProvider, PostOfficeBranch postOfficeBranch, Integer reason, Integer isbounseBackUpdate, String fileBase64, String remarks, Integer paymentType, String accountNo, String acountName, Date modificationDate, Date creationDate, Integer modifiedBy, Integer createdBy) {
        this.accountType = accountType;
        this.bank = bank;
        this.beneficiary = beneficiary;
        this.branch = branch;
        this.mobileBankingProvider = mobileBankingProvider;
        this.postOfficeBranch = postOfficeBranch;
        this.reason = reason;
        this.isbounseBackUpdate = isbounseBackUpdate;
        this.fileBase64 = fileBase64;
        this.remarks = remarks;
        this.paymentType = paymentType;
        this.accountNo = accountNo;
        this.accountName = acountName;

    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public AccountType getAccountType() {
        return this.accountType;
    }

    public void setAccountType(AccountType accountType) {
        this.accountType = accountType;
    }

    /**
     *
     * @return
     */
    public Bank getBank() {
        return this.bank;
    }

    public void setBank(Bank bank) {
        this.bank = bank;
    }

    public Beneficiary getBeneficiary() {
        return this.beneficiary;
    }

    /**
     *
     * @param beneficiary
     */
    public void setBeneficiary(Beneficiary beneficiary) {
        this.beneficiary = beneficiary;
    }

    /**
     *
     * @return
     */
    public Branch getBranch() {
        return this.branch;
    }

    public void setBranch(Branch branch) {
        this.branch = branch;
    }

    /**
     *
     * @return
     */
    public MobileBankingProvider getMobileBankingProvider() {
        return this.mobileBankingProvider;
    }

    /**
     *
     * @param mobileBankingProvider
     */
    public void setMobileBankingProvider(MobileBankingProvider mobileBankingProvider) {
        this.mobileBankingProvider = mobileBankingProvider;
    }

    /**
     *
     * @return
     */
    public PostOfficeBranch getPostOfficeBranch() {
        return this.postOfficeBranch;
    }

    public void setPostOfficeBranch(PostOfficeBranch postOfficeBranch) {
        this.postOfficeBranch = postOfficeBranch;
    }

    /**
     *
     * @return
     */
    public Integer getReason() {
        return this.reason;
    }

    public void setReason(Integer reason) {
        this.reason = reason;
    }

    public Integer getIsbounseBackUpdate() {
        return this.isbounseBackUpdate;
    }

    public void setIsbounseBackUpdate(Integer isbounseBackUpdate) {
        this.isbounseBackUpdate = isbounseBackUpdate;
    }

    /**
     *
     * @return
     */
    public String getFileBase64() {
        return this.fileBase64;
    }

    public void setFileBase64(String file) {
        this.fileBase64 = file;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Integer getPaymentType() {
        return this.paymentType;
    }

    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     *
     * @return
     */
    public String getAccountNo() {
        return this.accountNo;
    }

    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    public String getAccountName() {
        return this.accountName;
    }

    public void setAccountName(String acountName) {
        this.accountName = acountName;
    }

}
